/*
 * Bilancio.java
 *
 * Created on 18 gennaio 2009, 19.43
 */

package it.softfood.GUI;

import org.jdesktop.application.FrameView;

/**
 *
 * @author  marcograsso
 */
public class Bilancio extends javax.swing.JPanel {

    /** Creates new form Bilancio */
    public Bilancio(FrameView frame, String tipologia) {
        this.frame = frame;
        this.tipologia = tipologia;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tabella_bilancio = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        Ok = new javax.swing.JButton();
        Annulla = new javax.swing.JButton();

        setName("Form"); // NOI18N
        setLayout(new java.awt.GridLayout(2, 1, 5, 5));

        jScrollPane2.setName("jScrollPane2"); // NOI18N
		
		if(tipologia.equalsIgnoreCase("Mensile")){
		
			tabella_bilancio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Giorno", "Euro"
            }
         ));
			
		}else{
			tabella_bilancio.setModel(new javax.swing.table.DefaultTableModel(
			new Object [][] {
				{null, null},
				{null, null},
				{null, null},
				{null, null}
			},
			new String [] {
			    "Mese", "Euro"
				}
			));
			
		
		}
		
		
		
		
		
		tabella_bilancio.setName("tabella_bilancio"); // NOI18N
        jScrollPane2.setViewportView(tabella_bilancio);

        add(jScrollPane2);

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new java.awt.GridLayout(1, 2, 5, 5));

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(it.softfood.GUI.Main.class).getContext().getResourceMap(Bilancio.class);
        Ok.setText(resourceMap.getString("Ok.text")); // NOI18N
        Ok.setName("Ok"); // NOI18N
        jPanel1.add(Ok);

        Annulla.setText(resourceMap.getString("Annulla.text")); // NOI18N
        Annulla.setName("Annulla"); // NOI18N
        jPanel1.add(Annulla);

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Annulla;
    private javax.swing.JButton Ok;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabella_bilancio;
    // End of variables declaration//GEN-END:variables
    private String tipologia;
    private FrameView frame;
}
