/*
 * Incasso.java
 *
 * Created on 17 gennaio 2009, 18.51
 */

package it.softfood.GUI;

import org.jdesktop.application.FrameView;

/**
 *
 * @author  marcograsso
 */
public class Incasso extends javax.swing.JPanel {

    /** Creates new form Incasso */
    public Incasso(FrameView frame, String tipologia) {
        this.frame = frame;
        this.tipologia = tipologia;
        initComponents();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabella = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bottoni = new javax.swing.JPanel();
        Ok = new javax.swing.JButton();
        Annulla = new javax.swing.JButton();

        setName("Form"); // NOI18N
        setLayout(new java.awt.GridLayout(2, 1, 5, 5));

        tabella.setName("tabella"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Giorno", "Euro"
            }
        ));
        jTable1.setName("jTable1"); // NOI18N
        tabella.setViewportView(jTable1);

        add(tabella);

        bottoni.setName("bottoni"); // NOI18N
        bottoni.setLayout(new java.awt.GridLayout(1, 2, 5, 5));

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(it.softfood.GUI.Main.class).getContext().getResourceMap(Incasso.class);
        Ok.setText(resourceMap.getString("Ok.text")); // NOI18N
        Ok.setName("Ok"); // NOI18N
        bottoni.add(Ok);

        Annulla.setText(resourceMap.getString("Annulla.text")); // NOI18N
        Annulla.setName("Annulla"); // NOI18N
        Annulla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnullaActionPerformed(evt);
            }
        });
        bottoni.add(Annulla);

        add(bottoni);
    }// </editor-fold>//GEN-END:initComponents

private void AnnullaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnullaActionPerformed
// TODO add your handling code here:
  
}//GEN-LAST:event_AnnullaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Annulla;
    private javax.swing.JButton Ok;
    private javax.swing.JPanel bottoni;
    private javax.swing.JTable jTable1;
    private javax.swing.JScrollPane tabella;
    // End of variables declaration//GEN-END:variables
    private String tipologia;
    private FrameView frame;
}
