/*
 * MainView.java
 */

package it.softfood.GUI;

import com.arjuna.ats.arjuna.DisposeRecord;
import org.jdesktop.application.Action;
import org.jdesktop.application.ResourceMap;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import org.jdesktop.application.TaskMonitor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import javax.swing.Icon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;

/**
 * The application's main frame.
 */
public class MainView extends FrameView {

    public MainView(SingleFrameApplication app) {
        super(app);
        frame = this;
        initComponents();

        tavoli = new Tavoli(this);
        setComponent(tavoli);


        // status bar initialization - message timeout, idle icon and busy animation, etc
        ResourceMap resourceMap = getResourceMap();
        int messageTimeout = resourceMap.getInteger("StatusBar.messageTimeout");
        messageTimer = new Timer(messageTimeout, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                statusMessageLabel.setText("");
            }
        });
        messageTimer.setRepeats(false);
        int busyAnimationRate = resourceMap.getInteger("StatusBar.busyAnimationRate");
        for (int i = 0; i < busyIcons.length; i++) {
            busyIcons[i] = resourceMap.getIcon("StatusBar.busyIcons[" + i + "]");
        }
        busyIconTimer = new Timer(busyAnimationRate, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                busyIconIndex = (busyIconIndex + 1) % busyIcons.length;
                statusAnimationLabel.setIcon(busyIcons[busyIconIndex]);
            }
        });
        idleIcon = resourceMap.getIcon("StatusBar.idleIcon");
        statusAnimationLabel.setIcon(idleIcon);
        progressBar.setVisible(false);

        // connecting action tasks to status bar via TaskMonitor
        TaskMonitor taskMonitor = new TaskMonitor(getApplication().getContext());
        taskMonitor.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                String propertyName = evt.getPropertyName();
                if ("started".equals(propertyName)) {
                    if (!busyIconTimer.isRunning()) {
                        statusAnimationLabel.setIcon(busyIcons[0]);
                        busyIconIndex = 0;
                        busyIconTimer.start();
                    }
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(true);
                } else if ("done".equals(propertyName)) {
                    busyIconTimer.stop();
                    statusAnimationLabel.setIcon(idleIcon);
                    progressBar.setVisible(false);
                    progressBar.setValue(0);
                } else if ("message".equals(propertyName)) {
                    String text = (String)(evt.getNewValue());
                    statusMessageLabel.setText((text == null) ? "" : text);
                    messageTimer.restart();
                } else if ("progress".equals(propertyName)) {
                    int value = (Integer)(evt.getNewValue());
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(false);
                    progressBar.setValue(value);
                }
            }
        });
    }

    @Action
    public void showAboutBox() {
        if (aboutBox == null) {
            JFrame mainFrame = Main.getApplication().getMainFrame();
            aboutBox = new MainAboutBox(mainFrame);
            aboutBox.setLocationRelativeTo(mainFrame);
        }
        Main.getApplication().show(aboutBox);
    }
  
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        testo = new javax.swing.JTextPane();
        menuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu fileMenu = new javax.swing.JMenu();
        spesa = new javax.swing.JMenu();
        spesa_giornaliera = new javax.swing.JMenuItem();
        spesa_mensile = new javax.swing.JMenuItem();
        spesa_annuale = new javax.swing.JMenuItem();
        incasso = new javax.swing.JMenu();
        incasso_giornaliero = new javax.swing.JMenuItem();
        incasso_mensile = new javax.swing.JMenuItem();
        incasso_annuale = new javax.swing.JMenuItem();
        bilancio = new javax.swing.JMenu();
        bilancio_mensile = new javax.swing.JMenuItem();
        bilancio_annuale = new javax.swing.JMenuItem();
        javax.swing.JMenuItem exitMenuItem = new javax.swing.JMenuItem();
        javax.swing.JMenu helpMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem aboutMenuItem = new javax.swing.JMenuItem();
        statusPanel = new javax.swing.JPanel();
        javax.swing.JSeparator statusPanelSeparator = new javax.swing.JSeparator();
        statusMessageLabel = new javax.swing.JLabel();
        statusAnimationLabel = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();

        mainPanel.setInheritsPopupMenu(true);
        mainPanel.setName("mainPanel"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(it.softfood.GUI.Main.class).getContext().getResourceMap(MainView.class);
        testo.setText(resourceMap.getString("testo.text")); // NOI18N
        testo.setName("testo"); // NOI18N
        jScrollPane1.setViewportView(testo);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        menuBar.setName("menuBar"); // NOI18N

        fileMenu.setText(resourceMap.getString("fileMenu.text")); // NOI18N
        fileMenu.setName("fileMenu"); // NOI18N

        spesa.setText(resourceMap.getString("spesa.text")); // NOI18N
        spesa.setName("spesa"); // NOI18N

        spesa_giornaliera.setText(resourceMap.getString("spesa_giornaliera.text")); // NOI18N
        spesa_giornaliera.setName("spesa_giornaliera"); // NOI18N
        spesa_giornaliera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spesa_giornalieraActionPerformed(evt);
            }
        });
        spesa.add(spesa_giornaliera);

        spesa_mensile.setText(resourceMap.getString("spesa_mensile.text")); // NOI18N
        spesa_mensile.setName("spesa_mensile"); // NOI18N
        spesa_mensile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spesa_mensileActionPerformed(evt);
            }
        });
        spesa.add(spesa_mensile);

        spesa_annuale.setText(resourceMap.getString("spesa_annuale.text")); // NOI18N
        spesa_annuale.setName("spesa_annuale"); // NOI18N
        spesa_annuale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spesa_annualeActionPerformed(evt);
            }
        });
        spesa.add(spesa_annuale);

        fileMenu.add(spesa);

        incasso.setText(resourceMap.getString("incasso.text")); // NOI18N
        incasso.setName("incasso"); // NOI18N

        incasso_giornaliero.setText(resourceMap.getString("incasso_giornaliero.text")); // NOI18N
        incasso_giornaliero.setName("incasso_giornaliero"); // NOI18N
        incasso_giornaliero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incasso_giornalieroActionPerformed(evt);
            }
        });
        incasso_giornaliero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                incasso_giornalieroMouseClicked(evt);
            }
        });
        incasso.add(incasso_giornaliero);

        incasso_mensile.setText(resourceMap.getString("incasso_mensile.text")); // NOI18N
        incasso_mensile.setName("incasso_mensile"); // NOI18N
        incasso_mensile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incasso_mensileActionPerformed(evt);
            }
        });
        incasso.add(incasso_mensile);

        incasso_annuale.setText(resourceMap.getString("incasso_annuale.text")); // NOI18N
        incasso_annuale.setName("incasso_annuale"); // NOI18N
        incasso_annuale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incasso_annualeActionPerformed(evt);
            }
        });
        incasso.add(incasso_annuale);

        fileMenu.add(incasso);

        bilancio.setText(resourceMap.getString("bilancio.text")); // NOI18N
        bilancio.setName("bilancio"); // NOI18N

        bilancio_mensile.setText(resourceMap.getString("bilancio_mensile.text")); // NOI18N
        bilancio_mensile.setName("bilancio_mensile"); // NOI18N
        bilancio_mensile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bilancio_mensileActionPerformed(evt);
            }
        });
        bilancio.add(bilancio_mensile);

        bilancio_annuale.setText(resourceMap.getString("bilancio_annuale.text")); // NOI18N
        bilancio_annuale.setName("bilancio_annuale"); // NOI18N
        bilancio_annuale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bilancio_annualeActionPerformed(evt);
            }
        });
        bilancio.add(bilancio_annuale);

        fileMenu.add(bilancio);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(it.softfood.GUI.Main.class).getContext().getActionMap(MainView.class, this);
        exitMenuItem.setAction(actionMap.get("quit")); // NOI18N
        exitMenuItem.setName("exitMenuItem"); // NOI18N
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setText(resourceMap.getString("helpMenu.text")); // NOI18N
        helpMenu.setName("helpMenu"); // NOI18N

        aboutMenuItem.setAction(actionMap.get("showAboutBox")); // NOI18N
        aboutMenuItem.setName("aboutMenuItem"); // NOI18N
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        statusPanel.setName("statusPanel"); // NOI18N

        statusPanelSeparator.setName("statusPanelSeparator"); // NOI18N

        statusMessageLabel.setName("statusMessageLabel"); // NOI18N

        statusAnimationLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusAnimationLabel.setName("statusAnimationLabel"); // NOI18N

        progressBar.setName("progressBar"); // NOI18N

        javax.swing.GroupLayout statusPanelLayout = new javax.swing.GroupLayout(statusPanel);
        statusPanel.setLayout(statusPanelLayout);
        statusPanelLayout.setHorizontalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statusPanelSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusMessageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusAnimationLabel)
                .addContainerGap())
        );
        statusPanelLayout.setVerticalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addComponent(statusPanelSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusMessageLabel)
                    .addComponent(statusAnimationLabel)
                    .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3))
        );

        setComponent(mainPanel);
        setMenuBar(menuBar);
        setStatusBar(statusPanel);
    }// </editor-fold>//GEN-END:initComponents

    
public void setActualPanel(JPanel actual){
    this.actual=actual;
}

public JPanel getActualPanel(){
    return actual;
}
private void spesa_giornalieraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spesa_giornalieraActionPerformed
// TODO add your handling code here:
       tavoli.setVisible(false);
   Spesa spesa = new Spesa(this,"Giornaliera");
   setComponent(spesa);

}//GEN-LAST:event_spesa_giornalieraActionPerformed

private void spesa_mensileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spesa_mensileActionPerformed
// TODO add your handling code here:
    Spesa spesa = new Spesa(frame,"Mensile");
    tavoli.setVisible(false);
    setComponent(spesa);
}//GEN-LAST:event_spesa_mensileActionPerformed

private void spesa_annualeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spesa_annualeActionPerformed
// TODO add your handling code here:
    tavoli.setVisible(false);
    Spesa spesa = new Spesa(frame,"Annuale");
    setComponent(spesa);
}//GEN-LAST:event_spesa_annualeActionPerformed

private void incasso_giornalieroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incasso_giornalieroActionPerformed
    tavoli.setVisible(false);   
    Incasso incasso = new Incasso(this,"Giornaliera");
    setComponent(incasso);
}//GEN-LAST:event_incasso_giornalieroActionPerformed

private void incasso_giornalieroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_incasso_giornalieroMouseClicked
// TODO add your handling code here:
   
}//GEN-LAST:event_incasso_giornalieroMouseClicked

private void incasso_mensileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incasso_mensileActionPerformed
// TODO add your handling code here:
      tavoli.setVisible(false);   
    Incasso incasso = new Incasso(this,"Mensile");
    setComponent(incasso);
}//GEN-LAST:event_incasso_mensileActionPerformed

private void incasso_annualeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incasso_annualeActionPerformed
// TODO add your handling code here:
      tavoli.setVisible(false);   
    Incasso incasso = new Incasso(this,"Annuale");
    setComponent(incasso);
}//GEN-LAST:event_incasso_annualeActionPerformed

private void bilancio_mensileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bilancio_mensileActionPerformed
// TODO add your handling code here:
    tavoli.setVisible(false);
    Bilancio bilancio = new Bilancio(this, "Mensile");
    setComponent(bilancio);
}//GEN-LAST:event_bilancio_mensileActionPerformed

private void bilancio_annualeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bilancio_annualeActionPerformed
// TODO add your handling code here:
    tavoli.setVisible(false);//GEN-LAST:event_bilancio_annualeActionPerformed
    Bilancio bilancio = new Bilancio(this, "Annuale");
    
    setComponent(bilancio);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu bilancio;
    private javax.swing.JMenuItem bilancio_annuale;
    private javax.swing.JMenuItem bilancio_mensile;
    private javax.swing.JMenu incasso;
    private javax.swing.JMenuItem incasso_annuale;
    private javax.swing.JMenuItem incasso_giornaliero;
    private javax.swing.JMenuItem incasso_mensile;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JMenu spesa;
    private javax.swing.JMenuItem spesa_annuale;
    private javax.swing.JMenuItem spesa_giornaliera;
    private javax.swing.JMenuItem spesa_mensile;
    private javax.swing.JLabel statusAnimationLabel;
    private javax.swing.JLabel statusMessageLabel;
    private javax.swing.JPanel statusPanel;
    private javax.swing.JTextPane testo;
    // End of variables declaration//GEN-END:variables

    private Tavoli tavoli;
    private final Timer messageTimer;
    private final Timer busyIconTimer;
    private final Icon idleIcon;
    private final Icon[] busyIcons = new Icon[15];
    private int busyIconIndex = 0;
    private FrameView frame;
    private JDialog aboutBox;
    private JPanel actual;
    
    
}
