/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Ordine.java
 *
 * Created on 15-gen-2009, 19.21.49
 */

package it.softfood.GUI;

import javax.swing.JFrame;
import org.jdesktop.application.FrameView;

/**
 *
 * @author marco
 */
public class Ordine extends javax.swing.JPanel {

    /** Creates new form Ordine */
    public Ordine(FrameView frame) {
        initComponents();
        this.frame = frame;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jPanel1 = new javax.swing.JPanel();
        Totale = new javax.swing.JCheckBox();
        Romana = new javax.swing.JCheckBox();
        Consumo = new javax.swing.JCheckBox();
        Bottoni = new javax.swing.JPanel();
        Ok = new javax.swing.JButton();
        Annulla = new javax.swing.JButton();

        setName("Form"); // NOI18N
        setLayout(new java.awt.GridLayout(3, 0, 5, 5));

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.setName("jList1"); // NOI18N
        jScrollPane1.setViewportView(jList1);

        add(jScrollPane1);

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new java.awt.GridLayout(1, 3, 5, 5));

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(it.softfood.GUI.Main.class).getContext().getResourceMap(Ordine.class);
        Totale.setText(resourceMap.getString("Totale.text")); // NOI18N
        Totale.setName("Totale"); // NOI18N
        jPanel1.add(Totale);

        Romana.setText(resourceMap.getString("Romana.text")); // NOI18N
        Romana.setName("Romana"); // NOI18N
        jPanel1.add(Romana);

        Consumo.setText(resourceMap.getString("Consumo.text")); // NOI18N
        Consumo.setName("Consumo"); // NOI18N
        jPanel1.add(Consumo);

        add(jPanel1);

        Bottoni.setName("Bottoni"); // NOI18N
        Bottoni.setLayout(new java.awt.GridLayout(1, 2, 5, 5));

        Ok.setText(resourceMap.getString("Ok.text")); // NOI18N
        Ok.setName("Ok"); // NOI18N
        Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkActionPerformed(evt);
            }
        });
        Bottoni.add(Ok);

        Annulla.setText(resourceMap.getString("Annulla.text")); // NOI18N
        Annulla.setName("Annulla"); // NOI18N
        Annulla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnullaActionPerformed(evt);
            }
        });
        Bottoni.add(Annulla);

        add(Bottoni);
    }// </editor-fold>//GEN-END:initComponents

    private void OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
            FrameView frame = Main.getApplication().getMainView();
            JFrame mainFrame = Main.getApplication().getMainFrame();
            Conferma conferma = new Conferma(mainFrame, true, frame, this);
          conferma.setLocationRelativeTo(mainFrame);

            Main.getApplication().show(conferma);
        
    }//GEN-LAST:event_OkActionPerformed

    private void AnnullaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnullaActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Tavoli tavoli = new Tavoli(frame);
        frame.setComponent(tavoli);
    }//GEN-LAST:event_AnnullaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Annulla;
    private javax.swing.JPanel Bottoni;
    private javax.swing.JCheckBox Consumo;
    private javax.swing.JButton Ok;
    private javax.swing.JCheckBox Romana;
    private javax.swing.JCheckBox Totale;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    private FrameView frame;
}
