/*
 * Spesa.java
 *
 * Created on 17 gennaio 2009, 13.29
 */
package it.softfood.GUI;

import org.jdesktop.application.FrameView;

/**
 *
 * @author  marcograsso
 */
public class Spesa extends javax.swing.JPanel {

    /** Creates new form Spesa */
    public Spesa(FrameView frame, String tipologia) {
        this.tipologia = tipologia;
        initComponents();
        this.frame = frame;
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spesa = new javax.swing.JScrollPane();
        tabella_spesa = new javax.swing.JTable();
        pannello_bottoni = new javax.swing.JPanel();
        Ok = new javax.swing.JButton();
        Annulla = new javax.swing.JButton();

        setName("Form"); // NOI18N
        setLayout(new java.awt.GridLayout(2, 0, 5, 5));

        spesa.setName("spesa"); // NOI18N
		if(tipologia.equalsIgnoreCase("Giornaliera")){
        tabella_spesa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Voce", "Costo"
            }
																	   ));
		}else if(tipologia.equalsIgnoreCase("Mensile")){
			tabella_spesa.setModel(new javax.swing.table.DefaultTableModel(
																		   new Object [][] {
																		   {null, null},
																		   {null, null},
																		   {null, null},
																		   {null, null}
																		   },
																		   new String [] {
																		   "Giorno", "Costo"
																		   }
								   ));
																		   
		}else{
																		   tabella_spesa.setModel(new javax.swing.table.DefaultTableModel(
																																		  new Object [][] {
																																		  {null, null},
																																		  {null, null},
																																		  {null, null},
																																		  {null, null}
																																		  },
																																		  new String [] {
																																		  "Mese", "Costo"
																																		  }
																																		  ));
		}
		
			
			
			
			tabella_spesa.setName("tabella_spesa"); // NOI18N
        spesa.setViewportView(tabella_spesa);

        add(spesa);

        pannello_bottoni.setName("pannello_bottoni"); // NOI18N
        pannello_bottoni.setLayout(new java.awt.GridLayout(1, 2, 5, 5));

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(it.softfood.GUI.Main.class).getContext().getResourceMap(Spesa.class);
        Ok.setText(resourceMap.getString("Ok.text")); // NOI18N
        Ok.setName("Ok"); // NOI18N
        Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkActionPerformed(evt);
            }
        });
        pannello_bottoni.add(Ok);

        Annulla.setText(resourceMap.getString("Annulla.text")); // NOI18N
        Annulla.setName("Annulla"); // NOI18N
        Annulla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnullaActionPerformed(evt);
            }
        });
        pannello_bottoni.add(Annulla);

        add(pannello_bottoni);
    }// </editor-fold>//GEN-END:initComponents

private void AnnullaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnullaActionPerformed
    
}//GEN-LAST:event_AnnullaActionPerformed

private void OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkActionPerformed
    
}//GEN-LAST:event_OkActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Annulla;
    private javax.swing.JButton Ok;
    private javax.swing.JPanel pannello_bottoni;
    private javax.swing.JScrollPane spesa;
    private javax.swing.JTable tabella_spesa;
    // End of variables declaration//GEN-END:variables
    private FrameView frame;
    private String tipologia;
    private Main main;
}
