/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Tavoli.java
 *
 * Created on 15-gen-2009, 19.18.04
 */

package it.softfood.GUI;

import java.sql.Connection;
import java.sql.Driver;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import org.jdesktop.application.FrameView;

/**
 *
 * @author marco
 */
public class Tavoli extends javax.swing.JPanel {

    /** Creates new form Tavoli */
    public Tavoli(FrameView frame) {
        
        initComponents();
        this.frame = frame;
        String driverName = "org.postgresql.Driver";
        String databaseURL = "jdbc:postgresql://localhost:5432/softfood";
        Connection connection = null;
        Class driverClass = null;
        Driver driver = null;
        String query = null;
        Statement statement = null;
        ResultSet rs = null;
        try{
            driverClass = Class.forName(driverName);
            driver = (Driver) driverClass.newInstance();
            connection = DriverManager.getConnection(databaseURL, "postgres","root");
            query = "SELECT id FROM tavolo;";// WHERE occupato = true; ";
            statement = connection.createStatement();
            rs = statement.executeQuery(query);
            String[] strings = new String[10];
            int i = 0;
            while(rs.next()){
                strings[i] = "Tavolo " + ((Integer) rs.getInt("id")).toString();
                System.out.println(strings[i]);
                i=i+1;
            }
        }catch(Exception e){
            System.out.println("ERRORE DATABASE 1 "+e);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        setName("Form"); // NOI18N
        setLayout(new java.awt.GridLayout(1, 0, 5, 5));

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Tavolo 1", "Tavolo 2", "Tavolo 3", "Tavolo 4", "Tavolo 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.setName("jList1"); // NOI18N
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        add(jScrollPane1);
    }// </editor-fold>//GEN-END:initComponents

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        Ordine ordine = new Ordine(frame);
        frame.setComponent(ordine);
    }//GEN-LAST:event_jList1MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    private FrameView frame;
}
