package it.softfood.GUI;

import it.softfood.entity.Ingrediente;
import it.softfood.facade.articolomenu.ArticoloMenuFacadeRemote;
import java.util.ArrayList;
import javax.naming.InitialContext;
import javax.naming.NamingException;
import org.jdesktop.application.FrameView;

/**
 * @author Maria Rosaria Paone
 * @author Marco Grasso
 * @author Francesco Pacilio
 */

public class Pietanza extends javax.swing.JPanel {

    private ArticoloMenuFacadeRemote articolo;
    
    private void initFacade(){
        try{
            InitialContext initial=new InitialContext();
            articolo = (ArticoloMenuFacadeRemote) initial.lookup("it.softfood.facade.articolomenu.ArticoloMenuFacade");
        }catch(NamingException e){
            System.err.println("Errore binding: ArticoloMenuFacade");
        }
    }

    public Pietanza(FrameView frame,Long tavolo,Long id,String tipo) {
        this.tavolo = tavolo;
        this.tipo = tipo;
        
        initComponents();
        initFacade();
        
        this.frame = frame;
        this.id=id;
        
        ArrayList<Ingrediente> ingredienti = (ArrayList<Ingrediente>) articolo.selezionaIngredientiPietanza(id);

        String ingr[]=new String[ingredienti.size()];
        int i=0;
        for(Ingrediente ingrediente:ingredienti)
            ingr[i++] = ingrediente.getNome();

        listaIngredienti.setListData(ingr);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ok = new javax.swing.JButton();
        Annulla = new javax.swing.JButton();
        Cancella = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Variante = new javax.swing.JEditorPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaIngredienti = new javax.swing.JList();

        setMaximumSize(new java.awt.Dimension(225, 450));
        setMinimumSize(new java.awt.Dimension(225, 450));
        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(225, 450));
        setLayout(new java.awt.BorderLayout(5, 5));

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new java.awt.GridLayout(1, 3));

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(it.softfood.GUI.Main.class).getContext().getResourceMap(Pietanza.class);
        ok.setText(resourceMap.getString("ok.text")); // NOI18N
        ok.setName("ok"); // NOI18N
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        jPanel1.add(ok);

        Annulla.setText(resourceMap.getString("Annulla.text")); // NOI18N
        Annulla.setName("Annulla"); // NOI18N
        Annulla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnullaActionPerformed(evt);
            }
        });
        jPanel1.add(Annulla);

        Cancella.setText(resourceMap.getString("Cancella.text")); // NOI18N
        Cancella.setName("Cancella"); // NOI18N
        Cancella.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancellaActionPerformed(evt);
            }
        });
        jPanel1.add(Cancella);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        Variante.setText(resourceMap.getString("Variante.text")); // NOI18N
        Variante.setMaximumSize(new java.awt.Dimension(0, 0));
        Variante.setMinimumSize(new java.awt.Dimension(0, 0));
        Variante.setName("Variante"); // NOI18N
        jScrollPane2.setViewportView(Variante);

        add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        listaIngredienti.setName("listaIngredienti"); // NOI18N
        jScrollPane1.setViewportView(listaIngredienti);

        add(jScrollPane1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        if(tipo.equalsIgnoreCase("bibite")){
              Bibite pannello=new Bibite(frame, tavolo);
              frame.setComponent(pannello);
          }else{
              Pannello_ordinazioni pannello = new Pannello_ordinazioni(frame, tavolo, tipo);
              frame.setComponent(pannello);
          }
        
        
    }//GEN-LAST:event_okActionPerformed

    private void AnnullaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnullaActionPerformed
        // TODO add your handling code here:
          this.setVisible(false);
          if(tipo.equalsIgnoreCase("bibite")){
              Bibite pannello=new Bibite(frame, tavolo);
              frame.setComponent(pannello);
          }else{
              Pannello_ordinazioni pannello = new Pannello_ordinazioni(frame, tavolo, tipo);
              frame.setComponent(pannello);
          }
      
    }//GEN-LAST:event_AnnullaActionPerformed

    private void CancellaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancellaActionPerformed
        // TODO add your handling code here:
            Variante.setText("");
    }//GEN-LAST:event_CancellaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Annulla;
    private javax.swing.JButton Cancella;
    private javax.swing.JEditorPane Variante;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList listaIngredienti;
    private javax.swing.JButton ok;
    // End of variables declaration//GEN-END:variables
    private FrameView frame;
    private Long tavolo;
    private Long id;
    private String tipo;
}
