/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Pietanza.java
 *
 * Created on 14-gen-2009, 15.57.47
 */

package it.softfood.GUI;

import org.jdesktop.application.FrameView;

/**
 *
 * @author mary
 */
public class Pietanza extends javax.swing.JPanel {

    /** Creates new form Pietanza */
    public Pietanza(FrameView frame) {
        initComponents();
        this.frame = frame;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ok = new javax.swing.JButton();
        Annulla = new javax.swing.JButton();
        Cancella = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Variante = new javax.swing.JEditorPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaIngredienti = new javax.swing.JList();

        setMaximumSize(new java.awt.Dimension(225, 450));
        setMinimumSize(new java.awt.Dimension(225, 450));
        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(225, 450));
        setLayout(new java.awt.BorderLayout(5, 5));

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new java.awt.GridLayout(1, 3));

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(it.softfood.GUI.Main.class).getContext().getResourceMap(Pietanza.class);
        ok.setText(resourceMap.getString("ok.text")); // NOI18N
        ok.setName("ok"); // NOI18N
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        jPanel1.add(ok);

        Annulla.setText(resourceMap.getString("Annulla.text")); // NOI18N
        Annulla.setName("Annulla"); // NOI18N
        Annulla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnullaActionPerformed(evt);
            }
        });
        jPanel1.add(Annulla);

        Cancella.setText(resourceMap.getString("Cancella.text")); // NOI18N
        Cancella.setName("Cancella"); // NOI18N
        Cancella.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancellaActionPerformed(evt);
            }
        });
        jPanel1.add(Cancella);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        Variante.setText(resourceMap.getString("Variante.text")); // NOI18N
        Variante.setMaximumSize(new java.awt.Dimension(0, 0));
        Variante.setMinimumSize(new java.awt.Dimension(0, 0));
        Variante.setName("Variante"); // NOI18N
        jScrollPane2.setViewportView(Variante);

        add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        listaIngredienti.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listaIngredienti.setName("listaIngredienti"); // NOI18N
        jScrollPane1.setViewportView(listaIngredienti);

        add(jScrollPane1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
       // Pietanze pietanze = new Pietanze(frame);
       // frame.setComponent(pietanze);
    }//GEN-LAST:event_okActionPerformed

    private void AnnullaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnullaActionPerformed
        // TODO add your handling code here:
          this.setVisible(false);
       // Pietanze pietanze = new Pietanze(frame);
       // frame.setComponent(pietanze);
      
    }//GEN-LAST:event_AnnullaActionPerformed

    private void CancellaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancellaActionPerformed
        // TODO add your handling code here:
             this.setVisible(false);
         Menu menu = new Menu(frame);
         frame.setComponent(menu);
    }//GEN-LAST:event_CancellaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Annulla;
    private javax.swing.JButton Cancella;
    private javax.swing.JEditorPane Variante;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList listaIngredienti;
    private javax.swing.JButton ok;
    // End of variables declaration//GEN-END:variables
    private FrameView frame;
}
