package it.softfood.entity;




/**
 * Entrata generated by hbm2java
 */

public class Entrata implements java.io.Serializable {

	private Long id;
	private Ordinazione ordinazione;
	private Registro registro;

	public Entrata() {
	}

	public Entrata(Long id, Ordinazione ordinazione, Registro registro) {
		this.id = id;
		this.ordinazione = ordinazione;
		this.registro = registro;
	}

	
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	
	public Ordinazione getOrdinazione() {
		return this.ordinazione;
	}

	public void setOrdinazione(Ordinazione ordinazione) {
		this.ordinazione = ordinazione;
	}

	
	public Registro getRegistro() {
		return this.registro;
	}

	public void setRegistro(Registro registro) {
		this.registro = registro;
	}
        
        @Override
	public boolean equals(Object arg0) {
		// TODO Auto-generated method stub
		return super.equals(arg0);
	}

}
