package it.softfood.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
/*import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;*/

/**
 * Ordinazione generated by hbm2java
 */
//@Entity
//@Table(name = "ordinazione", schema = "public")
public class Ordinazione implements java.io.Serializable {

	private Long id;
	private Tavolo tavolo;
	private int coperti;
	private Date data;
	private Double sconto;
	private boolean terminato;
	private Double totale;
	private Set<Entrata> entratas = new HashSet<Entrata>(0);
	private Set<LineaOrdinazione> lineaOrdinaziones = new HashSet<LineaOrdinazione>(
			0);

	public Ordinazione() {
	}

	public Ordinazione(Long id, Tavolo tavolo, int coperti, Date data,
			boolean terminato) {
		this.id = id;
		this.tavolo = tavolo;
		this.coperti = coperti;
		this.data = data;
		this.terminato = terminato;
	}

	public Ordinazione(Long id, Tavolo tavolo, int coperti, Date data,
			Double sconto, boolean terminato, Double totale,
			Set<Entrata> entratas, Set<LineaOrdinazione> lineaOrdinaziones) {
		this.id = id;
		this.tavolo = tavolo;
		this.coperti = coperti;
		this.data = data;
		this.sconto = sconto;
		this.terminato = terminato;
		this.totale = totale;
		this.entratas = entratas;
		this.lineaOrdinaziones = lineaOrdinaziones;
	}

	//@Id
	//@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	//@ManyToOne(fetch = FetchType.LAZY)
	//@JoinColumn(name = "tavolo", nullable = false)
	public Tavolo getTavolo() {
		return this.tavolo;
	}

	public void setTavolo(Tavolo tavolo) {
		this.tavolo = tavolo;
	}

	//@Column(name = "coperti", nullable = false)
	public int getCoperti() {
		return this.coperti;
	}

	public void setCoperti(int coperti) {
		this.coperti = coperti;
	}

	//@Temporal(TemporalType.DATE)
	//@Column(name = "data", nullable = false, length = 13)
	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}

	//@Column(name = "sconto", precision = 17, scale = 17)
	public Double getSconto() {
		return this.sconto;
	}

	public void setSconto(Double sconto) {
		this.sconto = sconto;
	}

	//@Column(name = "terminato", nullable = false)
	public boolean isTerminato() {
		return this.terminato;
	}

	public void setTerminato(boolean terminato) {
		this.terminato = terminato;
	}

	//@Column(name = "totale", precision = 17, scale = 17)
	public Double getTotale() {
		return this.totale;
	}

	public void setTotale(Double totale) {
		this.totale = totale;
	}

	//@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "ordinazione")
	public Set<Entrata> getEntratas() {
		return this.entratas;
	}

	public void setEntratas(Set<Entrata> entratas) {
		this.entratas = entratas;
	}

	//@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "ordinazione")
	public Set<LineaOrdinazione> getLineaOrdinaziones() {
		return this.lineaOrdinaziones;
	}

	public void setLineaOrdinaziones(Set<LineaOrdinazione> lineaOrdinaziones) {
		this.lineaOrdinaziones = lineaOrdinaziones;
	}
        @Override
	public boolean equals(Object arg0) {
		// TODO Auto-generated method stub
		return super.equals(arg0);
	}

}
