/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Tavolo.java
 *
 * Created on 14-gen-2009, 20.05.08
 */

package it.softfood.GUI;

import java.awt.Frame;
import javax.swing.JFrame;
import org.jdesktop.application.FrameView;

/**
 *
 * @author mary
 */
public class Tavolo extends javax.swing.JPanel {

    /** Creates new form Tavolo */
    public Tavolo(FrameView frame) {
        initComponents();
        this.frame = frame;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        Ok = new javax.swing.JButton();
        Evaso = new javax.swing.JButton();
        Annulla = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(400, 275));
        setMinimumSize(new java.awt.Dimension(400, 275));
        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(400, 275));
        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, new Boolean(true)},
                {null, null, null}
            },
            new String [] {
                "Pietanza", "Quantità", "Evaso"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setName("jTable1"); // NOI18N
        jScrollPane1.setViewportView(jTable1);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(it.softfood.GUI.Main.class).getContext().getResourceMap(Tavolo.class);
        jTable1.getColumnModel().getColumn(0).setHeaderValue(resourceMap.getString("jTable1.columnModel.title0")); // NOI18N
        jTable1.getColumnModel().getColumn(1).setHeaderValue(resourceMap.getString("jTable1.columnModel.title1")); // NOI18N
        jTable1.getColumnModel().getColumn(2).setHeaderValue(resourceMap.getString("jTable1.columnModel.title2")); // NOI18N

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setMaximumSize(new java.awt.Dimension(400, 50));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 50));
        jPanel1.setName("bottoni"); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 50));
        jPanel1.setLayout(new java.awt.GridLayout(1, 3, 5, 5));

        Ok.setText(resourceMap.getString("Ok.text")); // NOI18N
        Ok.setMaximumSize(new java.awt.Dimension(29, 10));
        Ok.setMinimumSize(new java.awt.Dimension(29, 10));
        Ok.setName("Ok"); // NOI18N
        Ok.setPreferredSize(new java.awt.Dimension(29, 10));
        Ok.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkActionPerformed(evt);
            }
        });
        jPanel1.add(Ok);

        Evaso.setText(resourceMap.getString("Evaso.text")); // NOI18N
        Evaso.setMaximumSize(new java.awt.Dimension(50, 10));
        Evaso.setMinimumSize(new java.awt.Dimension(50, 10));
        Evaso.setName("Evaso"); // NOI18N
        Evaso.setPreferredSize(new java.awt.Dimension(50, 10));
        Evaso.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Evaso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EvasoActionPerformed(evt);
            }
        });
        jPanel1.add(Evaso);

        Annulla.setText(resourceMap.getString("Annulla.text")); // NOI18N
        Annulla.setMaximumSize(new java.awt.Dimension(59, 10));
        Annulla.setMinimumSize(new java.awt.Dimension(59, 10));
        Annulla.setName("Annulla"); // NOI18N
        Annulla.setPreferredSize(new java.awt.Dimension(59, 10));
        Annulla.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Annulla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnullaActionPerformed(evt);
            }
        });
        jPanel1.add(Annulla);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void EvasoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EvasoActionPerformed
        // TODO add your handling code here:
            FrameView frame = Main.getApplication().getMainView();
            JFrame mainFrame = Main.getApplication().getMainFrame();
            Conferma conferma = new Conferma(mainFrame, true, frame, this);
            conferma.setLocationRelativeTo(mainFrame);

            Main.getApplication().show(conferma);
        
        
        
    }//GEN-LAST:event_EvasoActionPerformed

    private void AnnullaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnullaActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Ordine ordine = new Ordine(frame);
        frame.setComponent(ordine);

    }//GEN-LAST:event_AnnullaActionPerformed

    private void OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Pietanza pietanza = new Pietanza(frame);
        frame.setComponent(pietanza);
    }//GEN-LAST:event_OkActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Annulla;
    private javax.swing.JButton Evaso;
    private javax.swing.JButton Ok;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    private FrameView frame;
}
