/*
 * Nuova_bevanda.java
 *
 * Created on 19 aprile 2009, 19.22
 */

package it.softfood.GUI;

import java.util.HashSet;

import it.softfood.entity.Bevanda;
import it.softfood.entity.BevandaMagazzino;
import it.softfood.entity.User;
import it.softfood.enumeration.TipoPietanza;
import it.softfood.facade.POSArticoloMenuFacade;

/**
 *
 * @author  marcograsso
 */
public class Nuova_bevanda extends javax.swing.JPanel {

    private MainView frame;
    private Bevanda bevanda;
    private String tipo;
    private POSArticoloMenuFacade articolofacade;
    private User role;
    /** Creates new form Nuova_bevanda */
    public Nuova_bevanda(MainView frame, Bevanda bevanda, String tipo) {
        this.bevanda=bevanda;
        this.frame=frame;
        this.tipo=tipo;
        initComponents();
        role=frame.getUser();
        articolofacade=new POSArticoloMenuFacade();
        
        jLabel3.setText(jLabel3.getText()+" (ml)");
        jLabel4.setText(jLabel4.getText()+" (ml)");
        
        
        
        if(tipo.equalsIgnoreCase("MODIFICA")){
        	jTextField1.setText(bevanda.getNome());
        	jTextArea1.setText(bevanda.getDescrizione());
        	jTextField2.setText(bevanda.getCapacita().toString());
        	try{
        		jTextField3.setText(new Integer(((BevandaMagazzino)bevanda.getBevandaMagazzinos().toArray()[0]).getQuantita()).toString());
        	}catch(Exception e){
        		jTextField3.setText("0");
        	}
        }
        	
    }



	/** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(600, 500));
        setMinimumSize(new java.awt.Dimension(600, 500));
        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(600, 500));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new java.awt.GridLayout(4, 2, 20, 5));

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(it.softfood.GUI.Main.class).getContext().getResourceMap(Nuova_bevanda.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        jPanel1.add(jLabel1);

        jTextField1.setText(resourceMap.getString("jTextField1.text")); // NOI18N
        jTextField1.setName("jTextField1"); // NOI18N
        jPanel1.add(jTextField1);

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        jPanel1.add(jLabel2);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTextArea1.setColumns(20);
//        jTextArea1.setRows(5);
        jTextArea1.setAutoscrolls(false);
        jTextArea1.setName("jTextArea1"); // NOI18N
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        jPanel1.add(jLabel3);

        jTextField2.setText(resourceMap.getString("jTextField2.text")); // NOI18N
        jTextField2.setName("jTextField2"); // NOI18N
        jPanel1.add(jTextField2);

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N
        jPanel1.add(jLabel4);

        jTextField3.setText(resourceMap.getString("jTextField3.text")); // NOI18N
        jTextField3.setName("jTextField3"); // NOI18N
        jPanel1.add(jTextField3);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setLayout(new java.awt.GridLayout(1, 2, 5, 5));

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);

        add(jPanel2, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>                        

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
// TODO add your handling code here:
	
	if(tipo.equalsIgnoreCase("NUOVO"))
		bevanda=new Bevanda();
	bevanda.setTipoArticolo("Bevanda");
	bevanda.setTipoPietanza(TipoPietanza.BEVANDA.ordinal());
	bevanda.setNome(jTextField1.getText());
	bevanda.setCapacita(new Float(jTextField2.getText()));
	bevanda.setDescrizione(jTextArea1.getText());
	
	if(tipo.equalsIgnoreCase("NUOVO"))
		bevanda=(Bevanda) articolofacade.inserisciBevandaMenu(role, bevanda);
	
	HashSet<BevandaMagazzino> set=new HashSet<BevandaMagazzino>();
	
	BevandaMagazzino bevandaMagazzino=null;
	try{
		bevandaMagazzino = (BevandaMagazzino) bevanda.getBevandaMagazzinos().toArray()[0];
		bevandaMagazzino.setQuantita(new Integer(jTextField3.getText()));
		articolofacade.updateBevandaMagazzino(role, bevandaMagazzino);
	}catch(Exception e){
		bevandaMagazzino=articolofacade.inserisciBevandaMagazzino(role, bevanda.getId(), new Integer(jTextField3.getText()));
	}
	set.add(bevandaMagazzino);
	bevanda.setBevandaMagazzinos(set);
	
	articolofacade.updateBevanda(role, bevanda);
	
    frame.getActualPanel().setVisible(false);
    Visualizza visualizza=new Visualizza(frame,"Bevanda");
    frame.setActualPanel(visualizza);
    frame.setComponent(visualizza);
}                                        

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
// TODO add your handling code here:
    frame.getActualPanel().setVisible(false);
    Visualizza visualizza=new Visualizza(frame,"Bevanda");
    frame.setActualPanel(visualizza);
    frame.setComponent(visualizza);
}                                        


    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration                   

}

