package it.softfood.GUI;

import it.softfood.entity.User;
import it.softfood.facade.PDAUserFacade;

import org.jdesktop.application.FrameView;

/*
 * Login.java
 *
 * Created on 5 aprile 2009, 20.50
 */

/**
 * 
 * @author marcograsso
 */
public class Login extends javax.swing.JPanel {

	public PDAUserFacade userFacade;

	private FrameView frame;

	/** Creates new form Login */
	public Login(FrameView frame) {
		userFacade = new PDAUserFacade();
		this.frame = frame;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		text = new javax.swing.JPasswordField();
		jPanel2 = new javax.swing.JPanel();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		jButton5 = new javax.swing.JButton();
		jButton6 = new javax.swing.JButton();
		jButton7 = new javax.swing.JButton();
		jButton8 = new javax.swing.JButton();
		jButton9 = new javax.swing.JButton();
		jButton10 = new javax.swing.JButton();
		jButton11 = new javax.swing.JButton();
		jButton12 = new javax.swing.JButton();

		setMaximumSize(new java.awt.Dimension(225, 450));
		setMinimumSize(new java.awt.Dimension(225, 450));
		setLayout(new java.awt.GridLayout(2, 1));

		jPanel1.setName("jPanel1"); // NOI18N
		jPanel1.setLayout(new java.awt.GridLayout(2, 1));

		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel1.setText("INSERISCI PASSWORD:");
		jLabel1.setName("jLabel1"); // NOI18N
		jPanel1.add(jLabel1);

		jScrollPane1.setName("jScrollPane1"); // NOI18N

		text.setColumns(1);

		text.setName("text"); // NOI18N
		text.setSize(150, 10);
		text.setMaximumSize(new java.awt.Dimension(150, 10));
		jScrollPane1.setViewportView(text);

		jPanel1.add(jScrollPane1);

		add(jPanel1);

		jPanel2.setName("jPanel2"); // NOI18N
		jPanel2.setLayout(new java.awt.GridLayout(3, 4));

		jButton1.setText("0");
		jButton1.setName("jButton1"); // NOI18N
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
		jPanel2.add(jButton1);

		jButton2.setText("1");
		jButton2.setName("jButton2"); // NOI18N
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});
		jPanel2.add(jButton2);

		jButton3.setText("2");
		jButton3.setName("jButton3"); // NOI18N
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});
		jPanel2.add(jButton3);

		jButton4.setText("3");
		jButton4.setName("jButton4"); // NOI18N
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});
		jPanel2.add(jButton4);

		jButton5.setText("4");
		jButton5.setName("jButton5"); // NOI18N
		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton5ActionPerformed(evt);
			}
		});
		jPanel2.add(jButton5);

		jButton6.setText("5");
		jButton6.setName("jButton6"); // NOI18N
		jButton6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton6ActionPerformed(evt);
			}
		});
		jPanel2.add(jButton6);

		jButton7.setText("6");
		jButton7.setName("jButton7"); // NOI18N
		jButton7.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton7ActionPerformed(evt);
			}
		});
		jPanel2.add(jButton7);

		jButton8.setText("7");
		jButton8.setName("jButton8"); // NOI18N
		jButton8.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton8ActionPerformed(evt);
			}
		});
		jPanel2.add(jButton8);

		jButton9.setText("8");
		jButton9.setName("jButton9"); // NOI18N
		jButton9.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton9ActionPerformed(evt);
			}
		});
		jPanel2.add(jButton9);

		jButton10.setText("9");
		jButton10.setName("jButton10"); // NOI18N
		jButton10.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton10ActionPerformed(evt);
			}
		});
		jPanel2.add(jButton10);

		jButton11.setText("C");
		jButton11.setName("jButton11"); // NOI18N
		jButton11.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton11ActionPerformed(evt);
			}
		});
		jPanel2.add(jButton11);

		jButton12.setText("N");
		jButton12.setName("jButton12"); // NOI18N
		jButton12.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton12ActionPerformed(evt);
			}
		});
		jPanel2.add(jButton12);

		add(jPanel2);
	}// </editor-fold>//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
	// TODO add your handling code here:
		String area = text.getText();
		text.setText(area.concat("0"));
	}// GEN-LAST:event_jButton1ActionPerformed

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton4ActionPerformed
	// TODO add your handling code here:
		String area = text.getText();
		text.setText(area.concat("3"));
	}// GEN-LAST:event_jButton4ActionPerformed

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
	// TODO add your handling code here:
		String area = text.getText();
		text.setText(area.concat("1"));
	}// GEN-LAST:event_jButton2ActionPerformed

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
	// TODO add your handling code here:
		String area = text.getText();
		text.setText(area.concat("2"));
	}// GEN-LAST:event_jButton3ActionPerformed

	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton5ActionPerformed
	// TODO add your handling code here:
		String area = text.getText();
		text.setText(area.concat("4"));
	}// GEN-LAST:event_jButton5ActionPerformed

	private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton6ActionPerformed
	// TODO add your handling code here:
		String area = text.getText();
		text.setText(area.concat("5"));
	}// GEN-LAST:event_jButton6ActionPerformed

	private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton7ActionPerformed
	// TODO add your handling code here:
		String area = text.getText();
		text.setText(area.concat("6"));
	}// GEN-LAST:event_jButton7ActionPerformed

	private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton8ActionPerformed
	// TODO add your handling code here:
		String area = text.getText();
		text.setText(area.concat("7"));
	}// GEN-LAST:event_jButton8ActionPerformed

	private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton9ActionPerformed
	// TODO add your handling code here:
		String area = text.getText();
		text.setText(area.concat("8"));
	}// GEN-LAST:event_jButton9ActionPerformed

	private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton10ActionPerformed
	// TODO add your handling code here:
		String area = text.getText();
		text.setText(area.concat("9"));
	}// GEN-LAST:event_jButton10ActionPerformed

	private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton11ActionPerformed
	// TODO add your handling code here:
		String area = text.getText();
		if (!area.equalsIgnoreCase(""))
			text.setText(area.substring(0, area.length() - 1));
	}// GEN-LAST:event_jButton11ActionPerformed

	private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton12ActionPerformed
	// TODO add your handling code here:
		User u = null;
		try {
			u = userFacade.login("cameriere", text.getText());
			if (u == null)
				throw new Exception();
			this.setVisible(false);
			Ordine ordine = new Ordine(u, frame);
			frame.setComponent(ordine);
		} catch (Exception e) {
			this.setVisible(false);
			Login t = new Login(frame);
			frame.setComponent(t);
		}

	}// GEN-LAST:event_jButton12ActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton10;
	private javax.swing.JButton jButton11;
	private javax.swing.JButton jButton12;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton6;
	private javax.swing.JButton jButton7;
	private javax.swing.JButton jButton8;
	private javax.swing.JButton jButton9;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JPasswordField text;
	// End of variables declaration//GEN-END:variables

}
