package it.softfood.GUI;

import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import it.softfood.GUI.Login;
import it.softfood.entity.User;
import it.softfood.facade.PDAUserFacade;

/**
 * @author Maria Rosaria Paone
 * @author Marco Grasso
 * @author Francesco Pacilio
 */

public class MainView extends FrameView {
	
	private User u;
	private PDAUserFacade userFacade;

    public MainView(SingleFrameApplication app) {
        super(app);
        userFacade=new PDAUserFacade();
        u=null;
        initComponents();      
        
        Login ordine = new Login(this);
        setComponent(ordine);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        javax.swing.JMenu fileMenu = new javax.swing.JMenu();
        
        
        mainPanel.setMaximumSize(new java.awt.Dimension(225, 450));
        mainPanel.setMinimumSize(new java.awt.Dimension(225, 450));
        mainPanel.setName("mainPanel"); // NOI18N
        mainPanel.setPreferredSize(new java.awt.Dimension(225, 450));
        mainPanel.setLayout(null);
        
        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        
        menuBar.setMaximumSize(new java.awt.Dimension(600, 22));
        menuBar.setMinimumSize(new java.awt.Dimension(600, 22));
        menuBar.setName("menuBar"); // NOI18N
        menuBar.setPreferredSize(new java.awt.Dimension(600, 22));
        
        fileMenu.setText("File"); // NOI18N
        fileMenu.setName("fileMenu"); // NOI18N
        
        jMenuItem1.setText("Logout"); // NOI18N
        jMenuItem1.setEnabled(false);
        jMenuItem1.setName("jMenuItem1"); // NOI18N
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        fileMenu.add(jMenuItem1);
        
        menuBar.add(fileMenu);

        setComponent(mainPanel);
        setMenuBar(menuBar);
    }// </editor-fold>//GEN-END:initComponents
    
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
    	// TODO add your handling code here:
    		try{
    			userFacade.logout(this.getUser());
    		}catch(Exception e){
    			e.printStackTrace();
    		}
    	    this.getComponent().setVisible(false);
    	    Login login=new Login(this);
    	    this.disableLogout();
    	    setComponent(login);
    	}//GEN-LAST:event_jMenuItem1ActionPerformed
    
    public void enableLogout(){
        jMenuItem1.setEnabled(true);
    }
    
    public void disableLogout(){
        jMenuItem1.setEnabled(false);
    }
    
    public void setUser(User u){
    	this.u=u;
    }
    
    public User getUser(){
    	return u;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables
   
}
